import time
import os
from selenium import webdriver
from selenium.webdriver.common.by import By

browser= webdriver.Chrome("./chromedriver")
print('Going to the URL..')
os.system('cls')
browser.get("https://store.steampowered.com/login/?redir=steamawards%3Fsnr%3D1_4_661__promo-steamawards-voting&redir_ssl=1&snr=1_steamawards_4__global-header")
os.system('cls')
time.sleep(3)
os.system('title Steam Voting Bot | by sam1e')
os.system('cls')
print('Going to the URL..')
os.system('cls')
username = input('Enter username: ')
password = input('Enter password: ')
guardask = input('Does this account use Steam Guard via Mail/Phone? y/n: ')
if guardask == 'y':
        guard = input('Enter guard code: ')
        userput = browser.find_element(By.XPATH, "//*[@id='input_username']").click()
        userput2 = browser.find_element(By.XPATH, "//*[@id='input_username']").send_keys(username)
        passput = browser.find_element(By.XPATH, "//*[@id='input_password']").click()
        passput2 = browser.find_element(By.XPATH, "//*[@id='input_password']").send_keys(password)
        loginbtn = browser.find_element(By.XPATH, "//*[@id='login_btn_signin']/button").click()
        print('Logging in...')
        time.sleep(5)
        guardput = browser.find_element(By.XPATH, "//*[@id='twofactorcode_entry']").click()
        guardput2 = browser.find_element(By.XPATH, "//*[@id='twofactorcode_entry']").send_keys(guard)
        time.sleep(1)
        guardput3 = browser.find_element(By.XPATH, "//*[@id='login_twofactorauth_buttonset_entercode']/div[1]").click()
        time.sleep(5)
        os.system('cls')
        print('Logged in!')
        time.sleep(3)
        print('Clicking button 1...')
        votebtn1 = browser.find_element(By.XPATH, "//*[@id='option_61_1091500']/button/span").click()
        time.sleep(1)
        confbtn1 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 2...')
        votebtn2 = browser.find_element(By.XPATH, "//*[@id='option_62_1402320']/button/span").click()
        time.sleep(1)
        confbtn2 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 3...')
        votebtn3 = browser.find_element(By.XPATH, "//*[@id='option_63_252490']/button/span").click()
        time.sleep(1)
        confbtn3 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 4...')
        votebtn4 = browser.find_element(By.XPATH, "//*[@id='option_64_1240440']/button/span").click()
        time.sleep(1)
        confbtn4 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 5...')
        votebtn5 = browser.find_element(By.XPATH, "//*[@id='option_65_860510']/button/span").click()
        time.sleep(1)
        confbtn5 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 6...')
        votebtn6 = browser.find_element(By.XPATH, "//*[@id='option_66_1195290']/button/span").click()
        time.sleep(1)
        confbtn6 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 7...')
        votebtn7 = browser.find_element(By.XPATH, "//*[@id='option_67_1325200']/button/span").click()
        time.sleep(1)
        confbtn7 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 8...')
        votebtn8 = browser.find_element(By.XPATH, "//*[@id='option_68_1382330']/button/span").click()
        time.sleep(1)
        confbtn8 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 9...')
        votebtn9 = browser.find_element(By.XPATH, "//*[@id='option_69_1196590']/button/span").click()
        time.sleep(1)
        confbtn9 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 10...')
        votebtn10 = browser.find_element(By.XPATH, "//*[@id='option_70_1248130']/button/span").click()
        time.sleep(1)
        confbtn10 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Done!')
        input('Script by sam1e')
        time.sleep(5)

elif guardask == 'n':
        userput = browser.find_element(By.XPATH, "//*[@id='input_username']").click()
        userput2 = browser.find_element(By.XPATH, "//*[@id='input_username']").send_keys(username)
        passput = browser.find_element(By.XPATH, "//*[@id='input_password']").click()
        passput2 = browser.find_element(By.XPATH, "//*[@id='input_password']").send_keys(password)
        loginbtn = browser.find_element(By.XPATH, "//*[@id='login_btn_signin']/button").click()
        print('Logging in...')
        time.sleep(5)
        os.system('cls')
        print('Logged in!')
        time.sleep(3)
        print('Clicking button 1...')
        votebtn1 = browser.find_element(By.XPATH, "//*[@id='option_61_1091500']/button/span").click()
        time.sleep(1)
        confbtn1 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 2...')
        votebtn2 = browser.find_element(By.XPATH, "//*[@id='option_62_1402320']/button/span").click()
        time.sleep(1)
        confbtn2 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 3...')
        votebtn3 = browser.find_element(By.XPATH, "//*[@id='option_63_252490']/button/span").click()
        time.sleep(1)
        confbtn3 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 4...')
        votebtn4 = browser.find_element(By.XPATH, "//*[@id='option_64_1240440']/button/span").click()
        time.sleep(1)
        confbtn4 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 5...')
        votebtn5 = browser.find_element(By.XPATH, "//*[@id='option_65_860510']/button/span").click()
        time.sleep(1)
        confbtn5 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 6...')
        votebtn6 = browser.find_element(By.XPATH, "//*[@id='option_66_1195290']/button/span").click()
        time.sleep(1)
        confbtn6 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 7...')
        votebtn7 = browser.find_element(By.XPATH, "//*[@id='option_67_1325200']/button/span").click()
        time.sleep(1)
        confbtn7 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 8...')
        votebtn8 = browser.find_element(By.XPATH, "//*[@id='option_68_1382330']/button/span").click()
        time.sleep(1)
        confbtn8 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 9...')
        votebtn9 = browser.find_element(By.XPATH, "//*[@id='option_69_1196590']/button/span").click()
        time.sleep(1)
        confbtn9 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Clicking button 10...')
        votebtn10 = browser.find_element(By.XPATH, "//*[@id='option_70_1248130']/button/span").click()
        time.sleep(1)
        confbtn10 = browser.find_element(By.XPATH, "/html/body/div[2]/div[3]/div/div[2]/div[2]").click()
        time.sleep(1)
        print('Done!')
        print('Script by sam1e')
        time.sleep(5)
else:
    print('Invalid choice!')
    time.sleep(2)
    os.system('taskkill /f /im python.exe')